### ISSUE TITLE
allSales issue

### ISSUE THREAD

**Issue by puttiam** [puttiam/Fruitrouge-API#1]
- **allSales**
it should return a url of every brand image. It will be displayed on the product list screen in navigation bar. You can check it on image below.

 ![screen shot 2015-08-16 at 16 20 15](https://cloud.githubusercontent.com/assets/6847902/9293405/d6a48e84-4432-11e5-86a3-407d852143c5.png)

**Comment by ggrason** [comment]
Field urlMedia is added with the path to this picture.
