### ISSUE TITLE
Data source for left side menu (boutique and outlet sections)

### ISSUE THREAD

**Issue by puttiam** [puttiam/Fruitrouge-API#10]
As I understood app should show response of `getProductType` action on the left side menu. But how can I get a list of products by selected product type. @ggrason what do you think?

**Comment by puttiam** [comment]
@ggrason According to Phetdavanh's comment 
"[9/7/15, 18:22:54] Phetdavanh SISOMBATH: product type = category
[9/7/15, 18:23:12] Phetdavanh SISOMBATH: example « robe »
[9/7/15, 18:23:28] Phetdavanh SISOMBATH: you should retrieve all product for this category"

we need something like getProductsByProductType with ptype and corners parameters

**Comment by ggrason** [comment]
With saleProducts you can get all products from ptype X by calling it using ptype:X and corners:1 for corners part, which just means removing the idSale parameter.

I have requested that an outlet:0 / outlet:1 parameter is added so you can use it to search all products from the outlet with saleProducts. Because the other way is to use the outlet sale ID, but this one varies according to the season.

**Comment by ggrason** [comment]
"outlet" parameter works now.
{"outlet":1,"ptype":3,"offset":0,"chunks":10}
This will give you all dresses (ptype 3) from the outlet sale.
Note that if you include an idSale, it is ignored
"idSale":1234,"outlet":1 => idSale is overwritten by outlet ID.

**Comment by puttiam** [comment]
It was easier to make "corners:0" for outlet than creation of the new parameter "outlet", isn't it?

**Comment by puttiam** [comment]
@ggrason Please don't close issues. I will do it by myself when it will be tested or implemented.

**Comment by ggrason** [comment]
Point is there are 3 types of menus : private sales (corner = 0), corners (corner = 1), outlet (corner = 0 and special sale ID).
Using only corner = 0 could not be enough to specify outlet, you needed the outlet sale ID. But this one changes from 4 to 5 depending on the season, and this is never fixed. So you can not know which outlet ID is open, hence providing outlet = 1 was the simpliest option.
