### ISSUE TITLE
Change ptype to array in saleProducts action

### ISSUE THREAD

**Issue by puttiam** [puttiam/Fruitrouge-API#11]
We need change `ptype` parameter to array for implementing multiply selection of products

**Comment by ggrason** [comment]
to make it easier you just need to provide a list in the X-X-X-X format. 3-30 would mean dresses and tops. I asked for this to be handled. That format it already in use in the site code.

**Comment by ggrason** [comment]
Done in preprod. New test in sale.php form includes that example:
{"idSale":4161,"ptype":"37-41","offset":0,"chunks":10,"corners":0,"sort":4}
