### ISSUE TITLE
Change response of "getPassword" action

### ISSUE THREAD

**Issue by puttiam** [puttiam/Fruitrouge-API#12]
@ggrason I need response such as this one:
success(string value) - "password: 444" 
fail(string value) - "fail" or "wrong email"

Now it sends:
success - "1" ant it is wrong password for "444@email.com"
fail - "" (empty string). Empty string is already used for failed authorization.

**Comment by ggrason** [comment]
Actually the password isn't give by the site or app. It is sent by mail.
So if the string is empty, then the email is simply not recognized. If the result is "1" then the password has been sent back by mail.

**Comment by puttiam** [comment]
@ggrason Change response string from empty to "not responding" at least. Empty string response is already used for failed authorization.

**Comment by ggrason** [comment]
Result is changed to an array of int/text.
0 means success, 1 means failure. The text displays the according information.
