### ISSUE TITLE
Product types of sale from boutique or outlet section

### ISSUE THREAD

**Issue by puttiam** [puttiam/Fruitrouge-API#13]
How can I get product types of sale from boutique or outlet section?

Example on mobile version of website: Click "Boutique" -> Choose any sale -> click "Filter button"

You see product types for current sale. How can I fetch this data?

**Comment by ggrason** [comment]
For the moment I don't see a solution. I supposed you were already getting the current selection sale ID. But the selection can be multi-sale.

I guess the easiest solution will be to expand getTypesBySale. Using outlet parameter on one hand for outlet, using brand parameter on the other hand for corners.

**Comment by puttiam** [comment]
Ok. Let me know when it will be implemented.

**Comment by ggrason** [comment]
It's working.
{"brand":"ewa-i-walla_eva-tralala"} > gives you product types of both brands ewa-i-walla and eva-tralala
if there is idSale it returns this ID sale product types list.
If not, then it checks for sales considering brand parameter.
If none is provided, results is empty.

**Comment by puttiam** [comment]
How should request for outlet section look?
One sale has brand and idSale parameters

**Comment by puttiam** [comment]
response for action=getTypesBySale&params={"brand":"ballonet-socks"}
```
string(5) "1 = 1"
string(18) "p.idBrand IN (975)"
string(12) "s.corner = 1"
{
    "28": {
        "idType": "28",
        "href": "28",
        "title": "Lingerie",
        "subTypes": [
            {
                "idType": "34",
                "href": "34",
                "title": "Collants"
            }
        ]
    }
}
```
I guess you are editing webservice at the moment. Just saying

**Comment by ggrason** [comment]
Okay fixed.
For outlet it's the same as saleProducts : "outlet":1 replaces "idSale":<id outlet>.

So: if "brand" parameter is alone, it checks for those brands in corners.
if idSale parameter is alone, it checks for this idSale.
if idSale AND brand are provided, it checks for those brands in this idSale.

{"brand":"angels-never-die"} > all Angels Never Die products in corners.
{"idSale":1234,"brand":"angels-never-die"} > all AND products in this specific sale
{"outlet":1,"brand":"angels-never-die"} > all AND products in the outlet
{"outlet":1} all products in outlet (basically same as getProductType with {"corners":0})
{"idSale":1234} all products in this specific sale

**Comment by puttiam** [comment]
Boutique section. I get error in parsing of response of request.
Body of request: `action=getTypesBySale&params={"brand":"bohemia"}`
Error: `Badly formed object around character 459.`

**Comment by ggrason** [comment]
Do you encounter the issue again ? Because inbetween the preproduction DB has been updated with production data and the error does not happen anymore.
