### ISSUE TITLE
4 types of prices

### ISSUE THREAD

**Issue by puttiam** [puttiam/Fruitrouge-API#15]
@ggrason There are 4 types of prices. Explain please what means every type. Which types and where should be used on the basket screen?

```
 {
                    boughtPrice = "<null>";
                    category = "<null>";
                    endPrice = 10;
                    idModel = 1;
                    idProduct = 0;
                    modelSize = "";
                    productBaseName = "";
                    productColor = "Carte VIP";
                    productPrice = "10.00";
                    productType = "";
                    publicPrice = "<null>";
                    quantity = 0;
                    realIdSale = 0;
                    reduction = 0;
                }
```

**Comment by ggrason** [comment]
don't care about bought price.
publicPrice is the normal shop price, if it's 0 or equal to productPrice do not display it, else it should be "instead of <publicPrice>"
productPrice is the normal product price
endPrice is the normal product price minus the reductions (like -10% on the whole basket).

**Comment by ggrason** [comment]
Is this request still open ? What is required ?
