### ISSUE TITLE
User webservices

### ISSUE THREAD

**Issue by puttiam** [puttiam/Fruitrouge-API#17]
First of all we need a webservice that returns user model response. It will have only the one parameter "user ID".

**"updateMember":**

1. There is server-side validation of password. It doesn't allow pasword's length be less than 5 characters but this validations is missed in registration webservice.

**"updateNewletter":**

1. I need a list of states of `receiveSaleEmail` parameter ("weekly","daily",etc.).

**"parrainage"**

1. Is it like a "Send gift" feature?

**Comment by ggrason** [comment]
getMember WS is added.

**Comment by puttiam** [comment]
getMember WS must be the same as response of authent and register WS
For now types of `civility` parameter are different (string in getMember WS and integer in others)

**Comment by puttiam** [comment]
For request 
```
action=updateMember&params={"civility":"M","lastname":"LASTNAME","firstname":"Firstname","jourNaissance":5,"moisNaissance":03,"anneeNaissance":2015,"email":"denis.samokhin2011@gmail.com","password":"55555","confirmpassword":"55555"}
```
Sometimes I get response
```
(
<null>,
Merci de remplir correctement tous les champs obligatoiresLe mot de passe doit comporter 5 caractu00e8res minimum
)
```
I change name values sometimes it works, sometimes it doesn't.

**Comment by ggrason** [comment]
I could identify the problem as being the month of birth (moisNaissance), "03" is expected to be a string with quotes, so it works either by setting 3 or "03" but not 03.

**Comment by ggrason** [comment]
civility type fixed in getMember

**Comment by ggrason** [comment]
- updateNewsletter:
'daily', 'weekly', 'monthly','alertes'
- parrainage:
it's sponsorship. You send a mail to friends to subscribe. If they do and place an order, you receive a 10€ voucher.
- updateMember:
Need to discuss this but I don't think it's a big issue. Point is it works as is on the mobile version already as it seems. The registration function is kinda special, it comes from a special function that allow registration without password.

**Comment by puttiam** [comment]
@ggrason "updateNewsletter: 'daily', 'weekly', 'monthly','alertes'" 
What about 'no subscription' state?

**Comment by ggrason** [comment]
Any other state is handled as an unsubscription. So you can just set it to an empty string and it will unsubscribe the client.
