### ISSUE TITLE
Address webservices

### ISSUE THREAD

**Issue by puttiam** [puttiam/Fruitrouge-API#18]
Same for these webservices. As I noted in issue #17 all webservices MUST have a user id.
Can you explain how it works now? How server detects different clients?

**Comment by ggrason** [comment]
The user session is saved on the server and is between the server and the client terminal.
All you need is to authenticate the user when first coming. Then, the user id is a session parameter on server side that you don't need to provide.
It's the server's job to differenciate between different clients the same way it does with standard browsers

**Comment by puttiam** [comment]
OK. Thanks for your explanation
