### ISSUE TITLE
registration webservice update

### ISSUE THREAD

**Issue by puttiam** [puttiam/Fruitrouge-API#19]
Change response of "registration" webservice from "user id" to same response as after authorization.
Because there is no webservice to get user model by user id.

**Comment by ggrason** [comment]
I just did, so it returns 0 if there is a mistake, the user infos if it works. Ex:

[
    0,
    {
        "identifier": "4014170",
        "email": "testestest2@yopmail.com",
        "password": "testtest",
        "civility": 0,
        "firstname": "",
        "lastname": "",
        "birthdate": "0000-00-00",
        "optin": true,
        "partnerOptin": false
    }
]
