### ISSUE TITLE
saleProducts issue

### ISSUE THREAD

**Issue by puttiam** [puttiam/Fruitrouge-API#2]
- **saleProducts** 
 it should return `identifier`, `oldPrice`, `newPrice`, `title` of every product.

 ![screen shot 2015-08-16 at 16 20 15](https://cloud.githubusercontent.com/assets/6847902/9293405/d6a48e84-4432-11e5-86a3-407d852143c5.png)

**Comment by ggrason** [comment]
Memcache reloaded, it was an old cache.
