### ISSUE TITLE
I need required parameters for "addAddress" WS

### ISSUE THREAD

**Issue by puttiam** [puttiam/Fruitrouge-API#22]

**Comment by ggrason** [comment]
addressLabel, addressFirstname, addressLastname, zipcode, city, address1, phoneNumber, idCountry (1 for France) are mandatory. As well as the "action" field set to "insert".

company isn't mandatory, province isn't mandatory except for country Spain.
And I think you need an additionnal WS to provide the list of countries. For now just work with 1 = France.
