### ISSUE TITLE
listAddress WS

### ISSUE THREAD

**Issue by puttiam** [puttiam/Fruitrouge-API#23]
1. User authorization
2. User goes to address screen
3. listAddress sends his address list
4. User relaunches application (Authorization state was saved)
5. User goes to address screen
6. listAddress sends list with 6507 items in it

Seems that server register new session after app relaunching. How we can fix that?

**Comment by ggrason** [comment]
For the moment I have absolutely no solution for this issue. Point with the old iOS application was that each time you started the app, it displayed a login screen with email/password saved. So you logged in each time.

If we're not using this approach anymore, I don't see any solution except adding idMember everywhere and not using sessions anymore.

**Comment by puttiam** [comment]
I implemented background authorization for user that has been already authorized before. So app creates session on every launch. No need to add idMember everywhere.

But address issue is not fixed. Now I can't detect the reason why I receive response with 6507 items

**Comment by ggrason** [comment]
There is so many items when the session member ID is equals to 0. We have that many wrong addresses in the DB linked to idMember = 0.
I changed the code so that when it is 0 it should not return anymore any address.

**Comment by puttiam** [comment]
OK, I am working with listAddress ws at the moment. All addresses disappeared :) I thought I did something wrong. Thanks
