### ISSUE TITLE
Promo codes WS

### ISSUE THREAD

**Issue by puttiam** [puttiam/Fruitrouge-API#24]
@ggrason can you explain me how to work with promo codes ws?

**Comment by ggrason** [comment]
I changed a lot the configuration to update the basket : selected address, promotional code, carriers and relay.

- addPromotionalCode : simply provide the promo code as entered by the client (like "5EUROS"). It will add it to the basket.
getCodePromos still provides a list of promo codes for the current users, but they might use other codes that are valid for everyone and not listed.
- addDeliveryAddress : just add the ID of the selected delivery address
- getCarriers : will provide you the list of carriers according to the selected address. It will tell you if kiala relays are possible, if the address is a local or international delivery, if delivery via TNT for business or TNT express is possible (french addresses). Each entry provides you the code of the carrier and display informations/price
- addCarrier : simply add the above code for the selected carrier (like "default", "tnt" ...)
- addRelay : if it's a relay, add it. You need the relay ID and country.
We need to discuss this point, I don't know at all how you can implement kiala solution into iOS. It's all about display and I can't help just with a WS. All I know you'd need is the current selected address' zipcode, to start the search.

With all of theses, the basket should update each time so using loadBasket you should retrieve the updated prices & such.

**Comment by puttiam** [comment]
http://locateandselect.kiala.com/info/ I've found this documentation
Let me know if it is right or wrong. Can you tell me what ws  I should use there?

But you can make a wrapper on server side. 
1. Server receives current selected address' zipcode from iOS, android or web client
2. Sends request to kiala server. 
3. Receives data
4. Sends data to client

**Comment by ggrason** [comment]
This is a pure HTML implementation. There is no option for Kiala integration directly inside an app ??? Cause then there's still so much to do and we have so many projects going on, I wasn't planning at all to work on Be2Bill first, Kiala neither <_< I thought an option was already discussed for this implementation.

**Comment by puttiam** [comment]
- addPromotionalCode ws: response 0 - fail, 1 - success, right?
which property of loadBasket response should be displayed as reduction?(i.e. -10 euro)

**Comment by ggrason** [comment]
For me it is always the opposite. 0 = success, 1 or more = fail with error code.
For this WS:
0 => success.
1 => error, either removing existing code or adding promo code to basket
2 => error, this promo code is not valid

**Comment by ggrason** [comment]
For the reduction, it depends on where you need to display it.

I made a basket from 2 products in 2 different sales:

{
    "mainOrderId": null,
    "subTotal": 43.5,
    "totalQuantity": 2,
    "saving": 95.5,
    "orderShippingAmount": 7.8,
    "tvaRate": "1.2",
    "tva": 6.53,
    "nbVouchers": "0",
    "voucherAmount": 10,
    "totalVoucherAmount": 0,
    "reductionAmount": 4.35,
    "reductionShipping": 0,
    "reductionCreditNote": 0,
    "maxReducCreditNote": 29.9,
    "realSales": {
        "4321": "4321",
        "4351": "4351"
    },
    "sales": {
        "4351": {
            "models": [
                {
                    "idModel": "4483655",
                    "idProduct": "603685",
                    "realIdSale": "4351",
                    "productType": "Tunique",
                    "productBaseName": "JOHANNA",
                    "productColor": null,
                    "modelSize": "TU=T36/40",
                    "productPrice": "21.00",
                    "publicPrice": "90.00",
                    "boughtPrice": "10.53",
                    "category": "20546",
                    "quantity": "1",
                    "reduction": 2.1,
                    "endPrice": 18.9,
                    "imageSmall": "http://media1.fruitrouge.com/data/sale/sale_4231/product_582885/small_1.jpg",
                    "imageMax": "http://media1.fruitrouge.com/data/sale/sale_4231/product_582885/max_1.jpg",
                    "available": 2
                }
            ],
            "subTotal": 21,
            "saving": 69,
            "orderShippingAmount": 3.9,
            "reductionAmount": 2.1,
            "reductionShippingAmount": 0,
            "orderAmount": 22.8,
            "vatRate": "1.2",
            "vatAmount": 3.15,
            "nbVouchers": 0,
            "reductionCreditNote": 0,
            "delivery": "Expu00e9dition pru00e9vue entre le 23/11/15 et le 30/11/15"
        },
        "4321": {
            "models": [
                {
                    "idModel": "4487608",
                    "idProduct": "605117",
                    "realIdSale": "4321",
                    "productType": "Pull",
                    "productBaseName": "CHARLOTTE",
                    "productColor": "ecru",
                    "modelSize": "TM/L=T38/42",
                    "productPrice": "22.50",
                    "publicPrice": "49.00",
                    "boughtPrice": "10.00",
                    "category": "20478",
                    "quantity": "1",
                    "reduction": 2.25,
                    "endPrice": 20.25,
                    "imageSmall": "http://media1.fruitrouge.com/data/sale/sale_4321/product_605117/small_1.jpg",
                    "imageMax": "http://media1.fruitrouge.com/data/sale/sale_4321/product_605117/max_1.jpg",
                    "available": 19
                }
            ],
            "subTotal": 22.5,
            "saving": 26.5,
            "orderShippingAmount": 3.9,
            "reductionAmount": 2.25,
            "reductionShippingAmount": 0,
            "orderAmount": 24.15,
            "vatRate": "1.2",
            "vatAmount": 3.38,
            "nbVouchers": 0,
            "reductionCreditNote": 0,
            "delivery": "Expu00e9dition pru00e9vue entre le 23/11/15 et le 30/11/15"
        }
    },
    "idPromotionalCode": "2167914",
    "infosCode": {
        "promotionalCode": "TESTGG10P",
        "amountPromotionalCode": "0",
        "reduction": "10",
        "applyOnShipping": "0",
        "applyOnSale": null,
        "applyOnCorners": null,
        "minimumAmount": "0",
        "applyOnProductNumber": null,
        "reductionNextProductNumber": "0",
        "reductionOnFirstProduct": null,
        "excludeReducedPrices": "0",
        "validation": true
    },
    "total": 46.95
}

Total reduction is in the main content:
"reductionAmount": 4.35

Reduction per sale is in each sale's content:
"reductionAmount": 2.1
"reductionAmount": 2.25

If the reduction applies on shipping then the fields are 
"reductionShipping": (amount) for global order
"reductionShippingAmount": (amount) for each sale

**Comment by ggrason** [comment]
WS is changed. Empty code does not remove the code anymore with addPromotionalCode, you need to use removePromotionalCode for that (no parameter).

return from addPromotionalCode:
0 : OK
1 : nothing changed (either no basket or basket already has this code)
2 : MySQL error
3 : Unknown code

return from removePromotionalCode:
0 : OK
1 : nothing changed (either no basket or basket already has no code)
2 : MySQL error

**Comment by puttiam** [comment]
:+1:
