### ISSUE TITLE
Bug on addToBasket method

### ISSUE THREAD

**Issue by puttiam** [puttiam/Fruitrouge-API#26]
I get successful response when I add product with "availability:0" to basket

**Comment by ggrason** [comment]
I can't reproduce it.

I'm trying with {"idModel":"4093317","quantity":"1"} which is this product :
http://preprod.fruitrouge.com/Produit_detail.php?id=3785&cat=19245&prod=509240&corners=1&hook=1
(size T4=T42)

The result is :
"Le produit Robe GUNNER sable T4=T42 n'est plus disponible dans les quantit&amp;eacute;s demand&amp;eacute;es"
(which means the product isn't available in desired quantities)

Using saleProducts with {"idSale":3785,"ptype":"3","offset":0,"chunks":10,"corners":0,"sort":4} this product is the first one. The result for this size:
           {
                "label": "T4=T42",
                "availability": 0,
                "model": "4093317"
            },
