### ISSUE TITLE
What parameters of Kiala point should be used?

### ISSUE THREAD

**Issue by puttiam** [puttiam/Fruitrouge-API#27]
What parameters of Kiala point  and what endpoint of fruitrouge webservices should be used?
I get these parameter of Kiala point
![screen shot 2015-11-12 at 16 07 06](https://cloud.githubusercontent.com/assets/6847902/11120318/7df75e3c-8957-11e5-9d89-864a1ee7cb7e.png)

**Comment by ggrason** [comment]
id + country code.
id should be a 5 digits code, country is FR or BE.
