### ISSUE TITLE
Add 'icon url' parameter to getCarriers WS

### ISSUE THREAD

**Issue by puttiam** [puttiam/Fruitrouge-API#28]
Add `icon url` parameter to getCarriers WS
![fr_livraison_iphone](https://cloud.githubusercontent.com/assets/6847902/11243392/6593cf7a-8e10-11e5-8ecd-4ea103ebca7e.jpg)

**Comment by ggrason** [comment]
It's been added !

**Comment by puttiam** [comment]
Thanks.
Please re-upload images to production server. I use 3rd party framework for downloading images. So I can't set Authorization header to request

**Comment by ggrason** [comment]
They are on prod, only the WS gives the URL according to the environment.
It's not the best but I changed the code to force URL from prod environment everywhere.

**Comment by puttiam** [comment]
http://www.fruitrouge.com/images/FR-fr/basket/Picto_KiaIa_Tunnel.png
This one doesn't work

**Comment by ggrason** [comment]
Fixed.
