### ISSUE TITLE
addRelay WS

### ISSUE THREAD

**Issue by puttiam** [puttiam/Fruitrouge-API#29]
I always get response "1". Is it fail code?

I send this `action=addRelay&params={"relayId":"01366","relayCountry":"FR"}`

**Comment by puttiam** [comment]
Got this response right now
<br />
<b>Fatal error</b>:  Call to undefined function getKPDetails() in <b>/data/www/pp_frt/front/WebService/mobile/class/CIosWebservice.php</b> on line <b>565</b><br />

**Comment by ggrason** [comment]
Fixed.
I used then addCarrier with {"carrier":"relay"}, then addRelay with {"relayId":"01366","relayCountry":"FR"}
It returned me:
```json
[
    "ZUZU BOOKS",
    "5, Rue De Metz",
    "75010",
    "PARIS",
    "A 50 m du th\u00e9atre Antoine"
]
```

**Comment by puttiam** [comment]
Confirmed. Thanks
