### ISSUE TITLE
Create getCountriesList WS

### ISSUE THREAD

**Issue by puttiam** [puttiam/Fruitrouge-API#31]
According to [your comment](https://github.com/puttiam/Fruitrouge-API/issues/22#issuecomment-147670241) I need getCountriesList WS (for Kiala)

**Comment by puttiam** [comment]
@ggrason You can also give me ID of Belgium

**Comment by ggrason** [comment]
France is 1, Belgium is 5.

**Comment by puttiam** [comment]
Thank you
