### ISSUE TITLE
I receive empty array after "saleProduct" request

### ISSUE THREAD

**Issue by puttiam** [puttiam/Fruitrouge-API#5]
![screen shot 2015-08-22 at 12 06 14](https://cloud.githubusercontent.com/assets/6847902/9423269/4cd4e6ac-48c6-11e5-8478-72b5651eac63.png)

![screen shot 2015-08-22 at 12 06 27](https://cloud.githubusercontent.com/assets/6847902/9423270/4cd6fc6c-48c6-11e5-9e5f-669073016190.png)

**Comment by ggrason** [comment]
ptype 40 is the issue, no products of this kind in sale 4113. Switching to "ptype":3 makes it work.
