### ISSUE TITLE
Sort parameter problem

### ISSUE THREAD

**Issue by puttiam** [puttiam/Fruitrouge-API#7]
I've found that there is no default value for sort parameter. I mean value when user doesn't choose type of sorting.

Solution: 
1) add 5th type of sorting "Default" => 0  
ex.: `params = {"idSale":4113,"ptype":0,"offset":0,"chunks":10,"corners":0,"sort":0}`

2) make sorting parameter as optional so I can request products without sorting type

ex.:` params = {"idSale":4113,"ptype":0,"offset":0,"chunks":10,"corners":0}`

**Comment by ggrason** [comment]
When the sort value isn't provided it defaults to sort value = 4. So you can already remove it, it is optionnal.
