### ISSUE TITLE
getHome sends wrong image for brand

### ISSUE THREAD

**Issue by puttiam** [puttiam/Fruitrouge-API#8]
```
{
        "brand": "pomme-rouge",
        "src": "http://media2.fruitrouge.com/data/home_corners/FR-fr/boutique_banner_secondrow_right.jpg?v=137"
  }
```
image for l33 brand

All sales have wrong images

**Comment by ggrason** [comment]
No worries, it's working except that the integration is wrong in preprod, it appears the same on http://m.preprod.fruitrouge.com/homeCorner.php
