### ISSUE TITLE
"spec" parameter

### ISSUE THREAD

**Issue by puttiam** [puttiam/Fruitrouge-API#9]
First item of getHome response for corners=1 has parameter `spec`. How I can fetch data if user clicks on this item?
```
{
        "spec": "news",
        "src": "http://media3.fruitrouge.com/data/home_corners/FR-fr/boutique-banner-top.jpg?v=137"
}
```

**Comment by puttiam** [comment]
@ggrason  should I use `sale` property to get list of products if `brand` is null?

**Comment by ggrason** [comment]
That "spec" line must be removed, I already asked for this but nothing was done yet.

**Comment by ggrason** [comment]
Spec parameter isn't displayed anymore.
